### PR TITLE
Correct probabilities

### PR DESCRIPTION
**Pull request by Mettbrot**
When using randint the border numbers can be selected to. So using randint(0, 100) actually gives one out of 101 thus changing the probability. Also I changed the used comparison to make it clearer how much procent the probability actually is. so randint (1, 10) <= 2 actually means 20 % (beeing 1 or 2 out of 10 possible, not out of 11 possible)

### CODE REVIEW

**Comment by Euphe** [comment]
I regret this decision. Please, next time before submitting a pull request update your fork. You were like 10-20 commits behind, now I have a lot of work to do.

**Comment by bb010g** [comment]
It should just be a simple [revert](http://gitready.com/intermediate/2009/03/16/rolling-back-changes-with-revert.html) to take out the damage.

**Comment by Mettbrot** [comment]
I am sorry but at the time I opened the PR it was up to date with the latest master. Could the problem be that you were working in your master branch locally and at the time you pushed you were not rebased onto origin/master (which included my changes)?

**Comment by Euphe** [comment]
I am still confused by what happened.
I merged the pull request from github, then commited my local changes.
Here my changes got applied:
https://github.com/Euphe/dungeon_bot/commit/e4bdd100d6f9a434f1c81afb1c8143600a71e9a4

I made some more changes, important ones.
Then I noticed a couple merge conflicts when pushing and resolved them:
https://github.com/Euphe/dungeon_bot/commit/eab0cd58f61cccc297333ba075101517bce19a82

Commited the merge resolution alongside my new changes.
https://github.com/Euphe/dungeon_bot/commit/eab0cd58f61cccc297333ba075101517bce19a82
And then noticed that many subtle chanes I made just before the pull request like ("qeue" to "queue" in all files) got reverted. It seems like your branch was one commit behind when you made the request (or you made the request before I pushed the last changes), but somehow git took them for being older changes.

My bad for not noticing when merge conflict appeared.

**Pull request merged**
